release: v0.7.0
openfga/js-sdk pull request #150
Opened 2024-08-31 01:04 UTC by evansims

## v0.7.0

- feat: enhancements to OpenTelemetry support (#149)

2024-08-31 01:05 UTC, evansims commented
Note: This expects https://github.com/openfga/js-sdk/pull/149 to be merged first.

2024-09-27 18:02 UTC, jimmyjames requested changes
just a suggestion for the changelog

2024-09-27 18:02 UTC, jimmyjames commented on CHANGELOG.md
> +- feat: enhancements to OpenTelemetry support (#149)
Should probably call out the breaking change

```suggestion
- feat!: enhancements to OpenTelemetry support (#149)

BREAKING CHANGE:

This version changes the way in which telemetry is configured and reported. See #149 for additional information.- feat!: enhancements to OpenTelemetry support (#149)
```

2024-09-27 18:06 UTC, jimmyjames approved these changes

2024-09-27 22:45 UTC, rhamzeh approved these changes

2024-09-27 23:10 UTC, merged